export const OneHitWonders = {
  1980: [
    { artist: 'Sophie & Magaly', title: 'Papa Pingouin' },
    { artist: 'Fabrice Bernard', title: 'La faute à Voltaire' },
    { artist: 'Nazaré Pereira', title: 'La marelle' },
  ],
  1981: [
    { artist: 'J.J. Lionel', title: 'La Danse des canards' },
    { artist: 'Janic Prévost', title: "J'veux d'la tendresse" },
    { artist: 'Pit et Rik', title: 'La cicrane et la froumi' },
    { artist: 'Patrick Coutin', title: "J'aime regarder les filles" },
    { artist: 'Martine Clémenceau', title: 'Solitaire' },
  ],
  1982: [
    { artist: 'F. R. David', title: 'Words' },
    { artist: 'Philippe Timsit', title: 'Henri, Porte des Lilas' },
    { artist: "Chagrin d'amour", title: "Chacun fait (c'qui lui plaît)" },
    { artist: 'Belgazou', title: 'Talk about it' },
    { artist: 'Élégance', title: "Vacances j'oublie tout" },
    { artist: 'Gérard Layani', title: 'Emeline' },
    { artist: 'Natali Kaufmann', title: 'Envie de traîner avec toi' },
  ],
  1983: [
    { artist: "Koeur's", title: 'Elodie' },
    { artist: 'Bandolero', title: 'Paris Latino' },
    { artist: 'Bruna Giraldi', title: "Il y a de l'amour dans l'air" },
  ],
  1984: [
    { artist: 'Bernard Menez', title: 'Jolie poupée' },
    { artist: 'Cookie Dingler', title: 'Femme libérée' },
    { artist: 'Peter et Sloane', title: 'Besoin de rien, envie de toi' },
    { artist: 'Laroche Valmont', title: "T'as le look, coco" },
    { artist: 'Vivien Savage', title: "La P'tite Lady" },
    { artist: 'Les Coco Girls', title: 'Ce mec est too much' },
  ],
  1985: [
    { artist: 'Sweet People', title: 'Adieu et bonne chance' },
    { artist: 'Bibie', title: 'Tout doucement' },
    { artist: 'Jean-Jacques Lafon', title: 'Le géant de papier' },
    { artist: 'Serge Delisle', title: 'Germaine' },
    { artist: 'Noé Willer', title: 'Toi, femme publique' },
    { artist: 'Bruno Grimaldi', title: 'Retour de manivelle' },
    { artist: 'Partenaire particulier', title: 'Partenaire particulier' },
  ],
  1986: [
    {
      artist: 'Stéphanie, Sandrine et les enfants de Bondy',
      title: 'Les bisous des bisounours',
    },
    { artist: 'Caroline Grimm', title: 'La vie sans toi' },
    { artist: 'Sabine Paturel', title: 'Les Bêtises' },
    { artist: 'Sandra Kim', title: "J'aime la vie" },
    { artist: 'Arnold Turboust feat. Zabou', title: 'Adélaïde' },
    { artist: 'Caroline Loeb', title: "C'est la ouate" },
    { artist: 'Les Ablettes', title: "Jackie s'en fout" },
    { artist: 'Luna Parker', title: "Tes états d'âme... Éric" },
    { artist: 'Philippe Russo', title: 'Magie noire' },
    { artist: 'Desireless', title: 'Voyage, Voyage' },
  ],
  1987: [
    { artist: 'Philippe Cataldo', title: 'Les Divas du dancing' },
    { artist: 'Licence IV', title: "Viens boire un p'tit coup à la maison" },
    { artist: 'Kazero', title: 'Thaï na na' },
    { artist: 'Robert Farel', title: 'Les petits boudins' },
    { artist: 'Pijon', title: 'Cache cache party' },
    { artist: 'Marijosé Alie', title: 'Caressé mwen' },
    { artist: 'Léopold Nord et Vous', title: "C'est l'amour" },
    { artist: 'Blues Trottoir', title: 'Un soir de pluie' },
    { artist: 'Christine Roque', title: "Premiers frissons d'amour" },
    { artist: 'Graziella de Michele', title: 'Pull-over blanc' },
    { artist: 'Éric Morena', title: 'Oh ! Mon bateau' },
    { artist: 'Animo', title: 'Des gens stricts' },
  ],
  1988: [
    { artist: 'Les Calamités', title: 'Vélomoteur' },
    { artist: 'Les Porte-Mentaux', title: 'Elsa Fräulein' },
    { artist: 'Shona', title: 'Elodie, mon rêve' },
    { artist: 'Tristan', title: 'Bonne bonne humeur ce matin' },
    { artist: 'À cause des garçons', title: 'À cause des garçons' },
    {
      artist: 'Claudia Phillips and the Kicks',
      title: 'Quel souci La Boétie !',
    },
    { artist: 'Début de soirée', title: 'Nuit de folie' },
    { artist: 'Paco', title: 'Amor de mis amores' },
    { artist: 'Sandy Stevens', title: "J'ai faim de toi" },
    { artist: 'Thierry Mutin', title: 'Sketch of Love' },
    { artist: 'Patsy', title: 'Liverpool' },
  ],
  1989: [
    { artist: 'Caroline Legrand', title: "J'aurais voulu te dire" },
    { artist: 'Jean-Pierre François', title: 'Je te survivrai' },
    { artist: 'Lova Moor', title: 'Et je danse' },
    { artist: 'Linda William', title: 'Traces' },
    { artist: 'Daniel Lanois', title: 'Jolie Louise' },
    { artist: 'Philippe Swan', title: 'Dans ma rue' },
    { artist: 'Atlantique', title: 'Poussée par le vent' },
    { artist: 'Ivanov', title: 'Les Nuits sans soleil' },
  ],
}
